from fastapi import APIRouter, Body
from pydantic import BaseModel
from typing import List, Dict
import numpy as np

from app.core.ga_engine import run_ga

router = APIRouter()

class Coverage(BaseModel):
    barangay: str
    fractionalAreaHa: float

class CanalInput(BaseModel):
    _id: str
    mainLateralId: str
    tbsByDamHa: float
    netWaterDemandM3: float
    seepageM3: float
    lossFactorPercentage: float
    coverage: List[Coverage]

class GAInput(BaseModel):
    scenario: str
    cropVariant: str
    totalSeasonalWaterSupplyM3: float
    readings: Dict[str, float]
    canalInput: List[CanalInput]


@router.post('/ga')

async def optimize_ga(payload: GAInput = Body(...)):
    # destructure payload
    scenario: str = payload.scenario
    crop_variant: str = payload.cropVariant
    total_water_available: float = float(payload.totalSeasonalWaterSupplyM3)
    readings: list = payload.readings

    canal_input: list = payload.canalInput
    canal_input_list: list = [c.model_dump() for c in canal_input]

    result = run_ga(canal_input_list, total_water_available)

    # return {
    #     "note": "response generated by Python GA service (debug)",
    #     "status": "completed",
    #     "payload": result
    # }